### ISSUE TITLE
Domain Registry interfaces

### ISSUE THREAD

**Issue by sgoendoer** [reTHINK-project/dev-registry-domain#1]
Which interfaces do we need for the Domain Registry?
User Identifiers will probably look like this: "http://mycspdomain.com/userid", e.g.: "http://facebook.com/fluffy123"

First, we need a way to retrieve a dataset for a user. This is the most basic function of the Domain Registry:

GET /{userid}

Next, we need the user to update his data (i.e. when the IP address changes or a new Hyperty is started):

PUT /{userid}

Question is whether we want to allow users to update sub-resources (e.g. ONE hyperty) or "just" the whole dataset as a whole?

Furthermore, we need interfaces/mechanisms for authentication

I would propose that configuration and initial setup are done by the CSP, which could provide a web interface for the user

**Comment by rjflp** [comment]
This is defined [here](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/DomainRegistryUserManual.md).
