### ISSUE TITLE
Integrate Matrix specific connector with the "common" connector

### ISSUE THREAD

**Issue by rjflp** [reTHINK-project/dev-registry-domain#14]
The connector implementation required some changes to be used by the Matrix Message Node. A fork was made and the changes were not ported to the connector implementation in this repository.

As there should be a single implementation, the two versions must be merged:
- The changes made for [Matrix](https://github.com/reTHINK-project/dev-msg-node-matrix/tree/master/src/mn/registry) should be integrated into this repository
- Afterwards, @sdruesedow should be contacted, so that the common registry connector can be tested and incorporated into Matrix

**Comment by rjflp** [comment]
This was solved in https://github.com/reTHINK-project/dev-registry-domain/commit/061dc0b4cb590fa01c3ab3fb670ff1a556b349b1

Waiting to remove connector fork on https://github.com/reTHINK-project/dev-msg-node-vertx/tree/master/src/js/connector

Waiting for NPM deployment of connector on the several Message Nodes.

**Comment by nunofmn** [comment]
Initial implementation of the connector as an NPM module is in `connector-refactor` branch.
After some integration testing with the msg-nodes implementations, will be merged in master.

**Installation**:
```
npm install github:rethink-project/dev-registry-domain#connector-refactor --save
```

**Comment by nunofmn** [comment]
Implemented in release 0.3.0 740550d.

The installation is slightly different from the mentioned in the last comment (links to a release tag instead of a branch).

**Installation:**
```
npm install github:rethink-project/dev-registry-domain#R0.3.0 --save
```

**Comment by sdruesedow** [comment]
I tested it with the (no)Matrix-MN and figured out that js-request.js does not return the http-statusCode to the callbacks.
Instead of 
>>>
    callback(null, response.getBody());
<<<
it should be:
>>>
   callback(null, response.getBody(), response.getCode());
<<<
in all 3 methods.
Please confirm!

**Comment by nunofmn** [comment]
Yes the `js-request.js`functions are incorrect.
I'm fixing it.

**Comment by nunofmn** [comment]
@sdruesedow already commited a fix to the master branch.
Since there could be some more problems in the integration with the Matrix-MN, could you please test with the version in the `master`branch? 

**Installation**:
```
npm install github:rethink-project/dev-registry-domain#master --save
```

Then if any more problems surface, I will fix them and bump the release.

Thanks.

**Comment by sdruesedow** [comment]
The RegistryConnector is now running as module in the nomatrix MN without any modifications necessary. Seems to work well so far.
