### ISSUE TITLE
Data in domain registry

### ISSUE THREAD

**Issue by sgoendoer** [reTHINK-project/dev-registry-domain#2]
Which data is necessary to be in the domain registry for a given user?

* UserID
* List of Hyperty instances (ip addresses, etc)

Optional values would be

* GUID
* timestamp of last change

**Comment by rjflp** [comment]
Will close issue as soon and documentation is updated to describe the json format for storing and retrieving data from the Domain Registry.

**Comment by rjflp** [comment]
REST format described [here](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/DomainRegistryUserManual.md)
