### ISSUE TITLE
docker image is not working on local environment

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-registry-domain#22]
Hi,
I have problem when executing `docker build -t domain-registry .`
![screenshot from 2016-07-18 16 42 30](https://cloud.githubusercontent.com/assets/15377466/16918686/d7d7effc-4d06-11e6-9f73-64ec1a576793.png)
 Is it due to my local environment ?
Cheers

**Comment by ruijose** [comment]
Are you executing the docker build command inside /dev-registry-domain/server? From your screenshot it seems that you are inside some other folder.

**Comment by jboulmal** [comment]
Actually I'm inside server/ folder where there is dockerfile. Let me try in another environment, may be probelm with my pc.

**Comment by jboulmal** [comment]
Well I have tried to build it in another Ubuntu 14.04 at home and it works fine.
I'll close this issue. Moreover,I'll try to find out what went wrong with my PC at work on weekends.
Cheers
