### ISSUE TITLE
domain-registry test

### ISSUE THREAD

**Issue by ingofriese** [reTHINK-project/dev-registry-domain#26]
Hi,

According to our last Friday discussion. I have a question.
I try currently to contact the domain-registry API of our domain: rethink-dev.tlabscloud.com

I get an answer {"message":"Not Found"}…I hope that’s from our domain registry ;-)
I looks that this is just a malformed request.
I open up a hyperty in our domain with the id: ingo.friese@gmail.com

What is the resulting request:

Is it  “.. /hyperty/user/user://rethink-dev.tlabscloud.com/ingo.friese@gmail.com” or the safe way (…hyperty/user/user%3A%2F%2Frethink-dev.tlabscloud.com&2Fingo%2Efriese%40gmail%2Ecom”)

is this right?

Many thanks…best Ingo

**Comment by ruijose** [comment]
Yes your request is correct. However, if you haven't registered any Hyperty associated with that user, a "not found" message is returned.

**Comment by ingofriese** [comment]
Today I checked how hyperties do the domain discovery.
So our domain name is rethink-dev.tlabscloud.com and ID ingo.friese@gmail.com
the request is formed to /user/user://gmail.com/ingo.friese (URL encoded) and is send to rethink-dev.tlabscloud.com
So infact we are talking about different domains (tlabscloud and gmail).
Anyway we can close this issue. (Maybe this should be clarified in the documentation) Thanx. Ingo
