### ISSUE TITLE
new tag in the domain registry 

### ISSUE THREAD

**Issue by ingofriese** [reTHINK-project/dev-registry-domain#27]
I'd like to propose a new tag in the domian-registry entry.

Current situation:
In the end of the discovery process today we have a list of different hyperties for a user.
There could be e.g. several hyperties of the same type (e.g. video/voice).
I'd like to add a tag that could be filled by the application or the user.
The values cloud be for example "work","private","my mobile","my talking smartwartch", "office","participate" etc.
The name of the tag could be "description","context" or what ever.

Then the discovery would look like this:

A user looks for another reTHINK user and finds finally a list of available hyperties
- > Ingo work (voice)
  -> Ingo home (voice)
  -> Ingo (chat)

What do you think?

**Comment by ruijose** [comment]
I think that proposal was already discussed (and implemented) [here](https://github.com/reTHINK-project/dev-registry-domain/issues/8).

**Comment by ingofriese** [comment]
My proposal is quit different because the discussion that you mentioned is about Hyperty types. 
They are implemented. I propose to add a "free-form" tag for  the user when he has  two or three Hyperties of the same kind running. He can add "business" or "private". That makes it easier to distiguish btw. several Hyperties.

Example: You (Rui Jose) have two Hyperties running. One on you Laptop in your office. And one on your chrome browser in your mobile phone.

When I (Ingo) discover Rui Jose's Hyperties
I see:
Hyperty url...423756926156969659 [voice/video]
Hyperty url...896734783467634756 [voice/video]
What Hypertie to select?

In fact it  would be great to have a free form tag. That you can add e.g. "mobil" or "office" or something else
Hyperty url...423756926156969659 [voice/video] [mobil]
Hyperty url...896734783467634756 [voice/video] [office]

**Comment by pchainho** [comment]
@ingofriese that's a good idea

I guess @ruijose is talking about the `tags` attribute currently supported by [Hyperty Data Object instance](https://github.com/reTHINK-project/specs/tree/p2p-specs/datamodel/core/hyperty-registry#hyperty-data-object-instance-or-hyperty-data-object-sessions) but not supported by the [Hyperty instance model](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/registry/Registry.js#L472). In terms of data model it could be a question of adding these attributes to [abstract Registry Data Object class](https://github.com/reTHINK-project/specs/tree/p2p-specs/datamodel/core/hyperty-registry#registry-data-model) and then they could be used either at Hyperty instance registrations or at Hyperty Data Object instance registrations. However it would have an impact at some runtime APIs namely on the [load](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/runtime/RuntimeUA.js#L172) and [registration](https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/registry/Registry.js#L472) of Hyperties in the runtime.

Anyway, I would support this extension.

**Comment by sbecot** [comment]
I'm not sure that the domain registry is the right place to do this. Global Registry may be more adapted, as it is filled by the user. Also, what you put in the tag is a part of the context (presence, availability...).

**Comment by sgoendoer** [comment]
I would object, as the GReg should be updates as little as possible.

Right now, the idea is that for each used CSP, the user has one UserID in the GlobalRegistry. If this is changed to tags, this would need to be updated quite often I guess. When the Hyperty X for video calls at CSP Y is shut down, this would need to be reflected in the GReg. If it is not, the tags would be outdated and hence incorrect most of the time.

**Comment by rjflp** [comment]
I like the concept but at the same time fear that a "free text" field has limited use for automation. Should we think of a classification?

@sgoendoer I agree.

**Comment by ingofriese** [comment]
@sbecot 
I think this kind of tag belongs to the actual Hyperty Instances. The Global registry does not know about how many instances are running. It just knows domain and user-id. The actual instances only the domain registry knows. So I think if we have to add it here.

**Comment by ingofriese** [comment]
I think free text is ok. We can limit it in terms of lenght or so but what speaks against free text. Classification should be up to applications. It could be also ignored if there is an automation application that does not want to rely on it.

**Comment by jmcrom** [comment]
on the best place to store such a tag I think it depends on the time cycle involved (GReg should be on long time cycle)

@ingofriese @rjflp @sgoendoer on the format it depends on the process using it: will dicovery service be the only one?

**Comment by ingofriese** [comment]
@jmcrom you can't store such a tag in the Global registry because its related to the actual hyperty instance.

I give you an example:
You can run two voice&video Hypertys in the orange.com domain.

When you asked the GReg there is only one entry called "userID"  jmchrome@gmail.com active at orange.com (only one line)

The Domain Registry is the only one that knows that you have 2 instances running one on your phone and on in your desktop PC. 
This means "free-style" tags like in your case "mobile" and "my desk" makes only sense in the domain registry

**Comment by ingofriese** [comment]
you can compare this tag with a display name.....could also be used when set up a call. But thats another itopic

**Comment by jmcrom** [comment]
okay if it is really a property of a particular instance it should be in the domain registry

yet another couple of questions: how this field will be provisioned? and which service apart discovery may use it?

**Comment by sdruesedow** [comment]
concerning the use of that field - I believe that the applications doing a search on the domain registry will have a big advantage. Currently the implemented discovery logic looks like "OK I get a list of discovered hyperties, but since I don't know the context and can't distinguish them - just the 'freshest' one wins!" 

For that reason we are always using different identities for doing simple tests - just because we can't easily distinguish registered hyperties. We currently just have the resource type etc.. If now the application has a chance to put an additional hint into the registration (like "at work", "at home", "mobile") the applications can make use of it for the selection of the proper communication peer.

**Comment by sbecot** [comment]
I don't want to mean that this field is not necessary, but I wonder if it is not hiding some deeper questions behind (for example routing policies, sens of information, etc...).

I could be "at work" and on my "mobile" at the same time. 
An hyperty appears in the domain registry means that you are connected. So if I want to reach you and have two ways to do it with a video call for example, I may not care to choose one or the other (except for tests purpose of course).
Also, I usually won't target an Hyperty (which is meaningless for the final user) but a service on a domain. What happens if you are logged on your mobile and your laptop on the same application "myApp" at the same time? 2 hyperties will appear in the domain registry of "myApp" I guess. But I just want to join Stephen at myApp. If I see that you have 2 devices that are video enabled, why should it be my responsibility to choose? I call Stephen, and you are accepting the call regarding your preferences, not mine.

**Comment by sbecot** [comment]
To complete the comment, I wonder if the discovery service has to display all hyperty instances, or only user->domain->reachable means. Then if I call the user, the routing policies are applied.
Advance option would allow to display all hyperty instances.

**Comment by ingofriese** [comment]
@sbecot 
You can compare it with a display name that the user or the application is free to choose. He can even leave it empty. And of course the aplication or the user can write something like "business and work" at the same time. He can also write he is "Batman" it free.

And my be you as a caller do not care about which hyperty to reach. But others my care.
According to your last problem with "myApp". Of course if there are 2 times "myApp" you are in the same situation. But if there s an indicator "mobile" you can use it but of course you are nt to oblidged to.

I agree with you in terms of: There might be more behind e.g. policies. We can discuss this. But don't tie it to the "display name field" because it is what it is. An optional field that is useful in many cases.

**Comment by sbecot** [comment]
Just as a reminder, in D1.1 requirement F15:
Incoming calls need to establish which endpoint is available, since each one is addressable separately by a unique global URL. Re-directing to another endpoint may be performed by the recipient web app.

**Comment by ingofriese** [comment]
Yes F15 describes exactly what domain registry is doing. Only available endpoints appaer in the domain registry. But if there there are several of the same kind (e.g. voice) how to desinguish? A free from tag could help here.

**Comment by sbecot** [comment]
Again, I'm not against the tag, but I just say that we should not rely too much on this.
And I'm afraid I don't understand F15 it the same way. It doesn't describe domain registry at all: incoming calls are managed by the recipient app. It says that they should be able to be redirected to another URL chosen by the recipient, which is rather different and is about policies.
To solve this issue, I would suggest to:
- add this tag if you think you need it.
- be careful to not mix what I consider a "debug" information and contextual/location/presence information which are managed by hyperties themselves and used by the applications (or discovery service). See D2.2 §5.8 and D5.1 §1.3.1

**Comment by ingofriese** [comment]
Yes, I agree in terms that we should not rely on it in terms of - we should not implememt e.g automatic procedures on top of it.

**Comment by rjflp** [comment]
This thread was been stopped for a while. Have we reached a conclusion? Should we close it as is?

**Comment by rjflp** [comment]
I'm closing this one as there has been no progress recently. Please re-open if needed.
