### ISSUE TITLE
Domain registry connector error handling update msg

### ISSUE THREAD

**Issue by jboulmal** [reTHINK-project/dev-registry-domain#30]
Hello,
While integrating the registry connector with msg-node-nodejs we got an error handelling `update` message according to specs [registration-messages](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md) this is check for `msg.body.value.url`. However,  update messages don't have `url in body of the message!`.
![screenshot from 2016-10-26 18 15 52](https://cloud.githubusercontent.com/assets/15377466/19734750/012c01b8-9ba9-11e6-8f9c-4e5d81a5c231.png)

**Comment by rjflp** [comment]
This is a discrepancy between runtime and connector versions.
We will make a release.

**Comment by nunofmn** [comment]
This problem is related with: https://github.com/reTHINK-project/dev-runtime-core/issues/117

Just waiting for confirmation of the status of the issue, before releasing a new connector version.

**Comment by nunofmn** [comment]
Fixed in Release 0.5.0.
