### ISSUE TITLE
Unregistration and Back to Live Update

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#31]
As specified at:
- https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#unregistration-request
- https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#update-registration-to-live
- https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#registry-temporarily-unavailable-responses

**Comment by nunofmn** [comment]
Added in release 0.5.0.
https://github.com/reTHINK-project/dev-registry-domain/releases/tag/R0.5.0
