### ISSUE TITLE
Extension to support Address Reusage

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#33]
Required for Address Reusage as specified at https://github.com/reTHINK-project/specs/tree/master/datamodel/core/hyperty-registry (highlighted with **Phase 2 new!!**)

To be aligned with runtime registry:

https://github.com/reTHINK-project/dev-runtime-core/issues/121

**Comment by nunofmn** [comment]
Added in Release 0.5.0.
