### ISSUE TITLE
Make the status page the default

### ISSUE THREAD

**Issue by rjflp** [reTHINK-project/dev-registry-domain#34]
When we access the root of the domain registry, we get a 404 error.
It would be nicer to either present a statistics page (like /live) or HTML with some information on what the server does.

**Comment by rjflp** [comment]
Paulo also asked for a way to browse the database content. Perhaps start with a list of users?

**Comment by ruijose** [comment]
The statistics page (/live) is now the root route. Basically the route "/" redirects to "/live".

**Comment by rjflp** [comment]
Browsing the user database would only be available for development. Production deployment would have this blocked.

**Comment by ruimangas** [comment]
Feature implemented and merged into develop. It will become available in the next release. @BernardoMG

**Comment by BernardoMG** [comment]
The Status Page for Domain Registry is available when is executed with a Development Environment tag. See [here](https://github.com/reTHINK-project/dev-registry-domain/tree/develop). The Status Page was developed using FreeMarker Template and shows all the information related with Domain Registry state, e.g, storage type, how many registered hyperties, how many users with registered hyperties and, per user, all the registered hyperties and their correspondent attributes.
