### ISSUE TITLE
Cannot get info with REST API

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-registry-domain#35]
I am using registry running locally.

I can registry one hyperty with toolkit.
![screenshot from 2016-10-31 12 26 20](https://cloud.githubusercontent.com/assets/11315256/19854212/c0883ef4-9f65-11e6-92e7-d758c5b96b3e.png)

When i try to get info about this hyperty using your rest API i always get 
```json
{
message: "Not Found"
}
```

As you can see,

![screenshot from 2016-10-31 12 27 33](https://cloud.githubusercontent.com/assets/11315256/19854250/f8a3eb94-9f65-11e6-8daa-612b0e835c2f.png)

**Comment by ruijose** [comment]
From those screenshots you registered a gmail.com/lduarte.suil user and later you requested a gmail/lduarte.suil . Those are different user ids.

**Comment by luistduarte** [comment]
That was a mistake, sorry
