### ISSUE TITLE
Cannot contact remote log4j

### ISSUE THREAD

**Issue by luistduarte** [reTHINK-project/dev-registry-domain#36]
With my Internet connection i dont have access to port 3456, and when i am running registry server locally, it try to contact your log4j remote server, because of it, it takes about 2minutes starting up

```
log4j.appender.tcp.port=3456
```
![screenshot from 2016-10-31 12 42 28](https://cloud.githubusercontent.com/assets/11315256/19854586/aa2b0b08-9f67-11e6-98b7-a4e820cad008.png)

**Comment by rjflp** [comment]
Just comment the following lines in the log4j.properties.

```
#log4j.appender.tcp=org.apache.log4j.net.SocketAppender
#log4j.appender.tcp.port=3456
#log4j.appender.tcp.ReconnectionDelay=10000
#log4j.appender.tcp.remoteHost=citysdk.tecnico.ulisboa.pt
```
We have all the servers sending logs to out log centralization platform for performance analysis and debug. Probably our firewall blocks this. Therefore, it needs to timeout before proceeding.
 
We'll change the default behavior.

**Comment by rjflp** [comment]
This issue has addressed in conversation with @luistduarte 
In the next release, we will have these lines commented by default.
