### ISSUE TITLE
Provide easy way to deploy with High Availability

### ISSUE THREAD

**Issue by rjflp** [reTHINK-project/dev-registry-domain#37]
Provide documentation and docker images to facilitate either high availability (7 docker images?) or development (single docker image) deployments.

**Comment by rjflp** [comment]
Status update:
Documentation updated [here](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/DomainRegistryUserManual.md)
-Already includes configuration of Cassandra for replication of database
-Still missing documentation on using load balancer for HTTP requests (HAproxy)
-Still missing documentation on using high availability for replicating load balancer (keepalived)

@pchainho can Altice Labs deploy Cassandra in your testbed? Perhaps using 2 ou 3 nodes? We can help you if needed.

**Comment by nunofmn** [comment]
The documentation has been updated [here](https://github.com/reTHINK-project/dev-registry-domain/blob/master/docs/DomainRegistryUserManual.md) to include the missing points.
