### ISSUE TITLE
Extension to Support P2P Stubs

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#38]
Required for P2P Stubs as specified at https://github.com/reTHINK-project/specs/tree/master/datamodel/core/hyperty-registry (highlighted with **Phase 2 new!!**)

To be aligned with runtime registry:

https://github.com/reTHINK-project/dev-runtime-core/issues/134

**Comment by nunofmn** [comment]
Added in Release 0.5.0.
