### ISSUE TITLE
Query per User GUID

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#42]
As specified [here](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#registry-data-object-search-per-guid)

**Comment by rjflp** [comment]
What is the use case? Can you provide an example?

**Comment by sbecot** [comment]
When and by whom this specification has been written/discussed/validated?

**Comment by pchainho** [comment]
Well, the GUID is in the Hyperty Registry data model since D2.2 

Regarding the message specs unfortunately I've been mostly the only one working on it. But any contributions are very much welcome :)

**Comment by rjflp** [comment]
@pchainho The use case? Just to make sure we participate in the validation of the design.

**Comment by sbecot** [comment]
I was asking, because @rjflp is responsible of the domain registry, so if the interface changes he should be aware of it. The fact that it is in the datamodel is a thing, the Query interface is another.

**Comment by pchainho** [comment]
right :)

In general it is to support the query of registered hyperties or objects independently of the user IdP Identifier associated to it. 

For example, since I have retrieved the GUID and associated dataset from the Global Reg and stored it in the Graph Connector, I can discover Hyperties in the different domain registries where the user has services registered / subscribed by using the GUID.

Of course, the user can use policies to control the access to hyperties discovery in the domain registry Hyperties including blocking this kind of query.

**Comment by rjflp** [comment]
Currently, this information can already be performed, although in a few more step: if we already "have retrieved the GUID and associated dataset from the Global Reg" then we can simply query the Domain Registry using the UserIds from the dataset obtained from the Global Reg. 

So, this is basically a more efficient way to do it?

**Comment by nunofmn** [comment]
Added in release 0.7.0.
