### ISSUE TITLE
Search by userid doesn't work

### ISSUE THREAD

**Issue by dvilchez** [reTHINK-project/dev-registry-domain#62]
<img width="1597" alt="screen-shot-2017-03-17-18-51-59" src="https://cloud.githubusercontent.com/assets/153025/24094658/f5f2f8e2-0d59-11e7-955b-adbb52186878.png">

**Comment by BernardoMG** [comment]
Hi @dvilchez .

Search by userid works. I think that what you did wrong was your encoding. You should try : `localhost:4568/hyperty/user/user%3A%2F%2Fgmail.com%2Fopenidtest10`

**Comment by dvilchez** [comment]
great!
