### ISSUE TITLE
Mechanism to clean outdated registry entries

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#7]
The Runtime registry should keep Registry entries active with a "heartbeat" kind of mechanism that updates the "lastModified" attribute. See [here](https://github.com/reTHINK-project/dev-service-framework/blob/d3.2-working-docs/docs/specs/messages/registration-messages.md#update-lastmodified-registration-request).

If possible the Runtime Registry unregisters "dead" registry entries. However if the Runtime does not shut down smoothly, this might not happen. To prevent having registry entries of dead hyperties or data objects, the Domain Registry should regularly clean its entries taking into account the value in the "lastModified" attribute.

The domain registry should also take into account the value in the "lastModified" attribute for search queries to avoid returning "dead" registry entries.

**Comment by ruijose** [comment]
This was implemented.

A configuration value is used to define the maximum amount of time (in seconds) a Hyperty stays in the server.
