### ISSUE TITLE
Code breaks at the check for java or js

### ISSUE THREAD

**Issue by jhamfler** [reTHINK-project/dev-registry-domain#9]
[This](https://github.com/reTHINK-project/dev-registry-domain/blob/master/connector/RegistryConnector.js#L20-L24) should be replaced with something like this to ensure that the code doesn't break:
```
if( typeof(engine) != 'undefined' &&
    typeof(engine.factory) != 'undefined' &&
    typeof(engine.factory.engineName) != 'undefined' &&
    typeof(engine.factory.engineName.contains) == 'function' &&
    engine.factory.engineName.contains("Nashorn")) {
  var RequestWrapper = require('./src/java-request');
}else {
  var RequestWrapper = require('./src/js-request');
}
```
I tested this and it should work in general.

**Comment by rjflp** [comment]
Solved https://github.com/reTHINK-project/dev-registry-domain/commit/061dc0b4cb590fa01c3ab3fb670ff1a556b349b1
